[package]
name = "backend_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.2"
actix-web = "4.2.1"
anyhow = "1.0.68"
dotenv = "0.15.0"
env_logger = "0.10.0"
log = "0.4.17"
